/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EMOJI_NORMAL_FILES           26
#define MMAP_EMOJI_NORMAL_CHECKSUM        0x2C8D

enum MMAP_EMOJI_NORMAL_LISTS {
    // 基础情绪文件
    MMAP_EMOJI_NORMAL_ANGRY_AAF = 0,        /*!< angry.aaf */
    MMAP_EMOJI_NORMAL_DIZZY_AAF = 1,        /*!< dizzy.aaf */
    MMAP_EMOJI_NORMAL_ENJOY_AAF = 2,        /*!< enjoy.aaf */
    MMAP_EMOJI_NORMAL_HAPPY_AAF = 3,        /*!< happy.aaf */
    MMAP_EMOJI_NORMAL_IDLE_AAF = 4,        /*!< idle.aaf */
    MMAP_EMOJI_NORMAL_LISTEN_AAF = 5,        /*!< listen.aaf */
    MMAP_EMOJI_NORMAL_SAD_AAF = 6,        /*!< sad.aaf */
    MMAP_EMOJI_NORMAL_SHOCKED_AAF = 7,        /*!< shocked.aaf */
    MMAP_EMOJI_NORMAL_THINKING_AAF = 8,        /*!< thinking.aaf */
    
    // 扩展情绪文件
    MMAP_EMOJI_NORMAL_COOL_AAF = 9,        /*!< cool.aaf */
    MMAP_EMOJI_NORMAL_SURPRISED_AAF = 10,        /*!< surprised.aaf */
    MMAP_EMOJI_NORMAL_FUNNY_AAF = 11,        /*!< funny.aaf */
    MMAP_EMOJI_NORMAL_CRYING_AAF = 12,        /*!< crying.aaf */
    MMAP_EMOJI_NORMAL_CONFUSED_AAF = 13,        /*!< confused.aaf */
    MMAP_EMOJI_NORMAL_SLEEPY_AAF = 14,        /*!< sleepy.aaf */
    MMAP_EMOJI_NORMAL_YAWN_AAF = 15,        /*!< yawn.aaf */
    MMAP_EMOJI_NORMAL_CURIOUS_AAF = 16,        /*!< curious.aaf */
    MMAP_EMOJI_NORMAL_SILLY_AAF = 17,        /*!< silly.aaf */
    
    // 图标和字体文件
    MMAP_EMOJI_NORMAL_ICON_BATTERY_BIN = 18,        /*!< icon_Battery.bin */
    MMAP_EMOJI_NORMAL_ICON_WIFI_FAILED_BIN = 19,        /*!< icon_WiFi_failed.bin */
    MMAP_EMOJI_NORMAL_ICON_MIC_BIN = 20,        /*!< icon_mic.bin */
    MMAP_EMOJI_NORMAL_ICON_SPEAKER_ZZZ_BIN = 21,        /*!< icon_speaker_zzz.bin */
    MMAP_EMOJI_NORMAL_ICON_WIFI_BIN = 22,        /*!< icon_wifi.bin */
    MMAP_EMOJI_NORMAL_KAITI_TTF = 23,        /*!< KaiTi.ttf */
};
